

services:
  mysqldb:
    image: mysql:8.0
    container_name: inventory-mysql
    environment:
      MYSQL_DATABASE: inventory_directory
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  backend-api:
    image: inventory-api:1.0
    container_name: inventory-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/inventory_directory?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update